### ISSUE TITLE
Can't install theme

### ISSUE THREAD

**Issue by DeMysteriisMundi** [szorfein/dotfiles#10]
Hello. I try install theme-city. My actions:
- install i3-gaps, kitty, termite, cava, polybar, zathura, vim, dina-font, xorg-xinit, xorg-server, rofi, feh, stow
- clone your repository to ~/Downloads
- cd dotfiles
- stow config -t ~
- stow images -t ~
- stow theme-city -t ~
- logout or reboot
- try to login to i3

And after this I see only theme-city background :c
Very want to try your theme and i3. Can you help me with this one, please?

**Comment by szorfein** [comment]
hi, did you installed polybar successfully? The last time i tried on archlinux, it failed.  And without polybar, the theme doesn't start correctly

**Comment by DeMysteriisMundi** [comment]
Hm... I will try again and write you about results.

**Comment by DeMysteriisMundi** [comment]
It got worse. Now standard i3 panel appears. It is updates every 10 sec. In background stayed SDDM login manager. And I can't interact with anything.

**Comment by szorfein** [comment]
You can  stop polybar temporary to see if it come from him, edit the `~/.config/i3/config` and change this:

    186  exec_always --no-startup-id ~/.config/polybar/launch.sh i3 

to:

    186  # exec_always --no-startup-id ~/.config/polybar/launch.sh i3

and start Xorg .

**Comment by DeMysteriisMundi** [comment]
Okay. Thanks for the help with the puzzle :) I just have complete your instructions, but it is not helped me.

I tried execute ~/.config/polybar/launch.sh and saw error "monitor eDP-1 not found or disconnected". Then I edited polybar config (changed eDP-1 to eDP, because xrandr said me, that my monitor named eDP). Now, when I execute launch.sh, bar starts. But now I have new errors:
![Screenshot_20190624_023119](https://user-images.githubusercontent.com/33153644/59983848-a73c8700-962c-11e9-85bc-712d518e9d98.png)

And configuration:
![Screenshot_20190624_023217](https://user-images.githubusercontent.com/33153644/59983855-bc191a80-962c-11e9-9201-5d6d7b48b378.png)

So, I'm sure, that daemons, that show status on the bar, just can't start. On the week I will try to make anything with it. I will be glad to your help and of course I will help you on my part.

**Comment by tjw0lf** [comment]
glad you got your polybar up. I tested it and worked like it should. 

those are font issues. install Noto fonts and Material Icons

**Comment by tjw0lf** [comment]
make sure you have mpd mpc ncmpcpp installed also and setup. then install polybar-git again so it build the correct stuff for mpd and stuff. try it again. should have less font issues

**Comment by szorfein** [comment]
Thanks for screenshot and the thing with `eDP`, for missing symbol, you have to install `material-icons`  https://aur.archlinux.org/cgit/aur.git/snapshot/ttf-material-icons-git.tar.gz  and `nerd-fonts-noto` on aur: https://aur.archlinux.org/cgit/aur.git/snapshot/nerd-fonts-noto-sans-regular-complete.tar.gz  
  
The ascii art of polybar do not display correctly with the dina-font, this is unfortunately normal :p.  

I have update the wiki with new dependencies and a troubleshooting section:  https://github.com/szorfein/dotfiles/wiki/theme-city

**Comment by szorfein** [comment]
the install of the theme-city should work now, i close, thanks for the issue.
