### ISSUE TITLE
when you get chance (sidebar)

### ISSUE THREAD

**Issue by tjw0lf** [szorfein/dotfiles#11]
I would like this sidebar would be pretty cool if you can add to your awesome. 
https://github.com/elenapan/dotfiles

**Comment by szorfein** [comment]
lol we'll see, first i have to finish my logout screen. mod4 + escape

**Comment by tjw0lf** [comment]
well, any tips? i tried adding this `local sidebar = require("noodle.sidebar")` to your rc.lua but didn't work gave me red errors.

**Comment by szorfein** [comment]
look all the `require(" ")` in the file, i see:  
    
    local disk_space = require("noodle.disk")
    local volume_bar = require("noodle.volume_bar")

etc, etc :)

**Comment by tjw0lf** [comment]
No go i put everything in. and got red errors after a restart. I will have to wait for ya. AwesomeWM isn't my strong suit ;( I i'm getting better but not a coder of AwesomeWM

**Comment by tjw0lf** [comment]
I got it :) Just issue i'm having with adding the titlebars .png in not sure why i see you had some in there but where red out.

https://i.imgur.com/pArNlKB.jpg

**Comment by szorfein** [comment]
Nice, it's normal that the top bar is sticking to the top of the screen ? it's supposed to be a gap between the top and the bar. :)

**Comment by tjw0lf** [comment]
Can you show me where it is probably changed I'll fix it

**Comment by szorfein** [comment]
In the theme file `~/.config/awesome/themes/anonymous/theme.lua`

    55 theme.screen_margin = dpi(6)

**Comment by tjw0lf** [comment]
i fixed it thanks You know how i can get two wibars in the you have at the top but trying to get the other one at the bottom

**Comment by szorfein** [comment]
For a bottom bar, just add `postion = "bottom"` at the `~/.config/awesome/bar_themes/anonymous.lua`

    147 s.useless_wibar = awful.wibar({ position = beautiful.wibar_position, screen = s, height = beautiful.screen_margin * 2, opacity = 0 })
    150 s.mywibox = awful.wibar({ height = beautiful.wibar_height, bg = beautiful.wibar_bg, width = dpi(1124) })

to:

    147 s.useless_wibar = awful.wibar({ position = "bottom", screen = s, height = beautiful.screen_margin * 2, opacity = 0 })
    150 s.mywibox = awful.wibar({ height = beautiful.wibar_height, bg = beautiful.wibar_bg, width = dpi(1124), position = "bottom"  })

**Comment by tjw0lf** [comment]
Thanks this was very helpfull i forgot to add these "" i didn't know you needed them :)

I see you posted another one BATTLESHIP. AWESOME! i'm going to install that one aswell i'm inlove with awesomeWM now :). I also commented on your reddit I'm Madscintist over there.

**Comment by szorfein** [comment]
Thanks, ok for Madscintist :) i will start to create sidebar very soon, i do not really know what i'm going to put in :), a todo list, few widgets which use [progressbar](https://awesomewm.org/doc/api/classes/wibox.widget.progressbar.html), a calendar, we'll see.

**Comment by tjw0lf** [comment]
if you can get spotify widget with coverart. an also mpd coverart that would be cool for those that use spotify. I always used spotify i have conky that shows coverart. but it would be cool to see widget like that and mpd.

**Comment by tjw0lf** [comment]
I'm Getting into mpd now. i really like that app you made for ncmpcpp its Awesome
