### ISSUE TITLE
I'm trying to get this in awesome

### ISSUE THREAD

**Issue by tjw0lf** [szorfein/dotfiles#13]
trying to get this into awesome. mpd coverart i see hes running vicious. but i'm stuck wiil thjis work in this awesome version. if your able to help. Thanks

https://www.reddit.com/r/unixporn/comments/c6cj50/awesome_we_live_in_a_society/

**Comment by szorfein** [comment]
i look for implement this, not yet stable for now :)
![](https://i.postimg.cc/Gtmpbwf2/popup.jpg)

**Comment by tjw0lf** [comment]
That's Cool Awesome.

I was trying to add this to the rc.lua. found in he's rc.lua. Which is a widget but he's and yours is way different. I don't know how to add it.
https://github.com/phallus/dotfiles/blob/master/.config/awesome/rc.lua

`-- mpd widget {{{
mpdwidget = wibox.widget.textbox()
monkfish.widgets.mpd.register(mpdwidget)
vicious.register(mpdwidget, vicious.widgets.mpd,
function (widget, args)
  if args["{state}"] == "Stop" then 
    muicon = colorizei(" ⮕ ", cyan, bgr)
    --muicon = colorizei(" ⮕ ", fgr, cyan)
    return ''..muicon..' not playing anything'
  else
    local artist = args["{Artist}"]
    local title = args["{Title}"]
    if args["{state}"] == "Pause" then
      muicon = colorizei(" ⮔ ", blue, bgr)
      --muicon = colorizei(" ⮔ ", fgr, cyan)
      full = colorizen(''..title..' by '..artist..'', fgr)
    elseif args["{state}"] == "Play" then
      muicon = colorizei(" ⮓ ", blue, bgr)
      --muicon = colorizei(" ⮓ ", fgr, cyan)
      full = colorizen(''..title..' by '..artist..'', fgr)
    else
      muicon = colorizei(" ⮕ ", red, bgr)
      --muicon = colorizei(" ⮕ ", fgr, cyan)
      full = '<span color="#d9798f">not playing anything</span>'
    end
    return ''..muicon..' '..full..' '
  end
end, 1)
--}}}`

**Comment by szorfein** [comment]
Well, if you want, you need: 

    monkfish.widgets.mpd.register(mpdwidget)

-> Need : `local monkfish = require("monkfish")`  and the directory [monkfish](https://github.com/phallus/dotfiles/tree/master/.config/awesome/monkfish)

    vicious.register(mpdwidget, vicious.widgets.mpd,

-> Need the [vicious lib](https://github.com/vicious-widgets/vicious).  

    muicon = colorizei(" ⮕ ", cyan, bgr)

-> here, you need the function `colorizei` which come from the line 83

    full = colorizen(''..title..' by '..artist..'', fgr)

-> Here, the function `colorizen` from the line 74

    fbg bgr red

-> Colors from the line 88

**Comment by tjw0lf** [comment]
WOW That's Cool @szorfein  

Well, I'm lost on that. The thing is I copied all he's folders to my awesome folder. I didn't see anything related to vicious in he's repo on github.

I did change the paths to my user. and put cover_fetcher in $HOME bin folder. I added what needed to for local. `local monkfish = require("monkfish")
local benis = require("benis")
local vicious = require("vicious")`

colorize i'm not really sure about. I just want to see if it runs. So i don't have to add the whole thing 
-- mpd widget {{{. It does go in rc.lua then?

> I'm still newbie to awesome trying to learn 

I really like yours better so i just might install BATTLESHIP aswell. Nice and clean :)

**Comment by szorfein** [comment]
![](https://i.postimg.cc/Y9NbJC05/player.png)

**Comment by tjw0lf** [comment]
Cool

I'm i able to put this in anonymous

**Comment by szorfein** [comment]
![](https://i.postimg.cc/90sXjdJ0/panel.png)

I've tested cover album with the tools [sacad](https://github.com/desbma/sacad).  About a working music directory, it look like this:  

```sh
$ tree
.
├── Frozen Synapse
│   ├── Frozen Synapse Soundtrack #04 - A Functioning God.ogg
│   ├── Frozen Synapse Soundtrack #05 - Switch.ogg
│   ├── Frozen Synapse Soundtrack #06 - Schism.ogg
│   ├── Frozen Synapse Soundtrack #09 - Nightpath.ogg
│   └── cover.png
├── The Social Network OST
│   ├── 3_14 Every Night (HD) - From the Soundtrack to 'The Social Network'.ogg
│   ├── Almost Home (HD) - From the Soundtrack to 'The Social Network'.opus
│   ├── In the Hall of the Mountain King (HD) - From the Soundtrack to 'The Social Network'.opus
│   ├── On We March (HD) - From the Soundtrack to 'The Social Network'.m4a
│   └── cover.png
```
An image should exist in the directory of the album (cover.png here) else use the default image (from images/anonymous.jpg).  
And few commands with sacad:

    $ sacad_r ~/musics 300 cover.png

Or one by one, if the command above don't find anything:

    $ sacad "Alexandre Desplat" "The Imitation Game" 300 /tmp/cover.png
    $ sacad "Trent Reznor" "The Social Network" 300 /tmp/cover.png

**Comment by tjw0lf** [comment]
<a href="https://imgur.com/89z3vQR"><img src="https://i.imgur.com/89z3vQR.gif" title="source: imgur.com" /></a>

I'm going to try it...

Also, the perc bar wasn't moving for me. And also was getting red error network monitor. This might be why not moving? How do i fix

**Comment by szorfein** [comment]
maybe, show me, please, the output of :

    $ ip a

**Comment by tjw0lf** [comment]
<a href="https://imgur.com/0NzrkyG"><img src="https://i.imgur.com/0NzrkyG.png" title="source: imgur.com" /></a>

My ip is enp0s3

I'm also using Virtualbox for setting things up

**Comment by tjw0lf** [comment]
I'm still getting that error

**Comment by tjw0lf** [comment]
how did you do that my cover not showing

**Comment by szorfein** [comment]
The widget should work with the last commit, thanks.  
You are free to post another issue for another problem :)

**Comment by tjw0lf** [comment]
How did you get the cover art in? Will, it automatically change on song play

**Comment by szorfein** [comment]
just edit the widget `mpc_time.lua` and change the line:

    98 ~/.config/awesome/widgets/audio.sh music_details /opt/musics

change `/opt/musics` with your music directory, if your follow the hierarchy of https://github.com/szorfein/dotfiles/issues/13#issuecomment-507744759 , it work fine.

**Comment by tjw0lf** [comment]
Mine didn't have   so i added it up top like yours

>  local MUSIC_DIR="/opt/musics""

- 
- `searchAlbumCover() {
-   local MUSIC_DIR="/opt/musics"
-   local MUSIC_DIR="$1"
-   local file="$(mpc --format %file% current)"
-   local album_dir="${file%/*}"
-   local cover=""`


I'm also getting still the red error. Might be because the network is wrong not sure what to add. I will send you my network info again. Thanks for all your help your amazing

**Comment by tjw0lf** [comment]
<a href="https://imgur.com/3Peuxx3"><img src="https://i.imgur.com/3Peuxx3.png" title="source: imgur.com" /></a>

<a href="https://imgur.com/25zcsN5"><img src="https://i.imgur.com/25zcsN5.png" title="source: imgur.com" /></a>

Here is everything the cover not showing up and the bar isn't moving. This network monitor issue again

**Comment by szorfein** [comment]
There are no images in your music directory, no jpg or png so this is normal, you have to download them manually or with sacad.

**Comment by tjw0lf** [comment]
I already copied them and pasted them when you commit them. :) I didn't use stow. What I'm i missing to add. My files are not linked anymore. i don't want them linked. the reason i didn't use stow i changed stuff manually. As you were doing it i changed it.

Is bar not moving because of network? The other reason i didn't use stow is because i'm in VirtualBox. once on my real metal i will stow everything.. :)

oh, you have to add cover manually I thought it finds it automatically?

**Comment by szorfein** [comment]
> oh, you have to add cover manually I thought it finds it automatically?

No, it's not automatically.  My widget only search cover in your music directory for a jpg or a png image but he doesn't download them.

**Comment by tjw0lf** [comment]
> No, it's not automatic. My widget only search cover in your music directory for a jpg or a png image but he does not download them.

Oh ok, i get it now :) Thanks

Yeah that's true :) I love stow. I just was eager to do it manually. I will use stow the more i use it the better i like it :)

**Comment by tjw0lf** [comment]
OK i stow awesomewm and the bar still isn't moving.

<a href="https://imgur.com/9llhaE8"><img src="https://i.imgur.com/9llhaE8.png" title="source: imgur.com" /></a>

**Comment by szorfein** [comment]
cool, all works, the script update all the 15sec, the progressbar (volume - green) seem to work, the little blue bar work too (6% done), the default image has the good size. Nice

**Comment by tjw0lf** [comment]
I'm not sure what you mean?

The progress bar does not move when the track is playing. (The green bar) next to the prev,play.puase,next. It's supposed to right? Also, the volume is not working again. Network error doesn't come up as of yet so that good.

**Comment by tjw0lf** [comment]
oh gosh i was misinformed. OK that bigger bar is the volume with the color. OK and blue line going is the bar. Ok the volume seems to work with PulseAudio only i put your asoundrc in and everything works. The only thing is i have to go to Output for the volume to be change in the widget. If i use mpc music daemon in the playback tab the volume will not go up or down in the widget.

<a href="https://imgur.com/SGJUSeq"><img src="https://i.imgur.com/SGJUSeq.gif" title="source: imgur.com" /></a>

**Comment by tjw0lf** [comment]
Also are you able to make the playing track that's blue line like the one in ncmpcpp? Or a bit bigger or something else its hard to see Where its it.

**Comment by szorfein** [comment]
sure it should be easy, i add this tomorrow :)

**Comment by tjw0lf** [comment]
Did you see this i put also

> Ok the volume seems to work with PulseAudio only i put your asoundrc in and everything works. The only thing is i have to go to Output for the volume to be change in the widget. If i use mpc music daemon in the playback tab the volume will not go up or down in the widget.

**Comment by szorfein** [comment]
i've change the character for the playback and the popup is now attached on the music icon rather than the mpc_time widget on the theme-battleship.  

About the volume, the progressbar only display the actual volume level but you can't increase or decrease the volume with the progressbar, the [widget](https://github.com/elenapan/dotfiles/blob/master/config/awesome/noodle/volume_bar.lua) of elenapan seem to make the same thing.  
To change the volume, i use the script [volume.sh](https://github.com/szorfein/dotfiles/blob/master/bin/bin/volume.sh) with Control + Alt + Up or Down,  
also my script work fine with alsa, for pulseaudio, look the script of [elenapan](https://github.com/elenapan/dotfiles/blob/master/bin/volume-control.sh)

**Comment by tjw0lf** [comment]
> add a big character to the audio.sh #13

nothing changed for me. i did stow -D awesomewm &&  stow awesomewm

can show me a screenshot of it

**Comment by tjw0lf** [comment]
Never Mind daa hit me on the head lol :) i forgot to redownload dotfiles to get the new mpc_buttens

**Comment by tjw0lf** [comment]
Where is that block coming from?

**Comment by szorfein** [comment]
you can change the character at `~/.config/awesome/widgets/audio.sh`

    108 bar="■"

It work better with only one character, but i've not tested all the variant
