### ISSUE TITLE
help setting zsh up

### ISSUE THREAD

**Issue by tjw0lf** [szorfein/dotfiles#14]
I'm having difficult time setting zsh up. Can you tell me what i have to do in order to get it working

Thanks

**Comment by szorfein** [comment]
Well, you only need to do:
   
    $ cd dotfiles
    $ ./install --zsh
    $ stow zsh

`./install --zsh` will install the plugins `oh-my-zsh` and `spaceship`.  
And i use zsh with keychain too if need install dependencies.

**Comment by tjw0lf** [comment]
stow zsh did not work. its not linked I believe. downloaded your dotfiles. I just copied the files in zsh folder to $HOME

**Comment by tjw0lf** [comment]
getting this
compdef: unknown command or service: rails

**Comment by szorfein** [comment]
it come from the `.zshrc`

    plugins=(git git-prompt ruby rails)

You can remove `ruby` and `rails`

    plugins=(git git-prompt)

The list of plugins can be show [here](https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins)

**Comment by tjw0lf** [comment]
you don't use ruby and rails? what is it used for.

**Comment by szorfein** [comment]
i use ruby and rails for other projects but not in this repository

**Comment by tjw0lf** [comment]
What are they used for. Also how would i go about adding more plugins. Like if i wanted them what would i do.

**Comment by szorfein** [comment]
> Completion plugins will let zsh know which arguments the package has so it can autocomplete.

**Comment by tjw0lf** [comment]
So let's say i wanted rails. how would i get it working?

**Comment by szorfein** [comment]
Well if you use ruby or rails, there are probably alrealy installed
  
    # pacman -S ruby rails

Add the completion:

    18 plugins=(git git-prompt ruby rails)

Reload zshrc

    $ source ~/.zshrc

and it's alll

**Comment by tjw0lf** [comment]
pacman -S ruby is installed but 
rails isn't in the AUR 
I checked yay couldn't find it

```
➜ source ~/.zshrc
compdef: unknown command or service: `rails
```

I need rails installed i think?

**Comment by tjw0lf** [comment]
I installed it like this `gem install rails`

```
➜ ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]

~ 
➜ rails -v
Rails 5.2.3
```
I still get
compdef: unknown command or service: rails

**Comment by tjw0lf** [comment]
I just removed rails like you said at the beginning :) That fixes that
