### ISSUE TITLE
I need help with neomutt. 

### ISSUE THREAD

**Issue by tjw0lf** [szorfein/dotfiles#15]
I want to set it up and was little confused at what to do. If you can tell me where stuff needs to go one by one. i can do it. I was little lost do i need a remote server or no.

WOW you have my name in the screenshot I posted that many times 1055 holy lol

**Comment by szorfein** [comment]
Yeah :p,  the config about mutt, neomutt will be really complex to setup, look my dots for example.  
For the same setup, you need `offlineimap` (IMAPS) , `msmtp` (SMTPS) , `neomutt` and GPG too to encrypt and decrypt mails.  

If you use gmail, look https://support.google.com/accounts/answer/6010255 and https://hobo.house/2017/07/17/using-offlineimap-with-the-gmail-imap-api/,

And google is you best friend too, some usefull post https://pbrisbin.com/posts/mutt_gmail_offlineimap/ , https://wiki.archlinux.org/index.php/OfflineIMAP , [Gnupg - neomutt](https://hispagatos.org/blog/2019-02-02-neomutt-gnupg-and-pass-howto/)

**Comment by tjw0lf** [comment]
Do i copy your mail folder in.. 

I will be just using gmail..

How do i get password and crt

**Comment by szorfein** [comment]
yes, you can use my `mail` directory`: https://github.com/szorfein/dotfiles/tree/master/mail , just edit files with your need.  

> do i need a remote server or no
No, i use gmail with msmtp, i don't use something like `dovecot` yet, witch require a server,

**Comment by tjw0lf** [comment]
Ok here's my password i got. i created for app. qmxxpfsfmrbtikd.  Where do i put it in which file?

Also do i need this. sslcacertfile = /etc/ssl/certs/ca-certificates.crt   where do get at if i do.

**Comment by tjw0lf** [comment]
I have heard protonmail is really good for privacy but the pro one is you have to pay for
https://protonmail.com/signup

**Comment by szorfein** [comment]
protonmail is nice, the problem is we need https://protonmail.com/bridge/ for use with offlineimap, and it's not free :(

**Comment by szorfein** [comment]
Add your gmail password in : offlineimap 

    remotepass = qmxxpfsfmrbtikd

and msmtp:

    password qmxxpfsfmrbtikd

look https://pbrisbin.com/posts/mutt_gmail_offlineimap/

**Comment by tjw0lf** [comment]
well i see your using this. 

`pythonfile = ~/.offlineimap.py`

`https://github.com/szorfein/dotfiles/blob/master/bin/bin/give_pass`

where would i put my passowrd in

**Comment by szorfein** [comment]
i use the script give_pass because my passwords are encrypt with gpg, but it's absolutely not mandatory.

**Comment by tjw0lf** [comment]
Well That's next thing i was going to ask how do i do that. How did you encrypt them gpg

**Comment by szorfein** [comment]
i know that you like read :), i've wrote some post about this:  
+ create a gpg key : https://szorfein.github.io/gpg/build-secure-gpg-key/
+ make password with gpg and vim: https://szorfein.github.io/vim/gpg/password/vim-gpg/

**Comment by tjw0lf** [comment]
That's to complex for me and hard. I'm sorry but my skill level can't go that far. Are you able to tell me what to do? Also, i do not use vim i never have i could learn it but i haven't yet never played with it

**Comment by szorfein** [comment]
you can skip gpg and use neomutt normally

**Comment by tjw0lf** [comment]
it won't be secure. will it

**Comment by szorfein** [comment]
just be carreful if you use git with your files of never send password on github.

**Comment by tjw0lf** [comment]
OK

**Comment by tjw0lf** [comment]
Where do put the mail folder in $HOME. or do i put all those files in .config

**Comment by szorfein** [comment]
in your $HOME

**Comment by tjw0lf** [comment]
I'm getting this

<a href="https://imgur.com/TdNBPrV"><img src="https://i.imgur.com/TdNBPrV.png" title="source: imgur.com" /></a>

**Comment by tjw0lf** [comment]
Now i'm getting this. I don't know what I'm doing wrong?

`(no mailbox)     0                                                         
/home/tj/.mails/gmail/INBOX: Not a directory (errno = 20)
`

**Comment by tjw0lf** [comment]
I got it working I copied one of the neomuttrc stuff you linked me i had to take out  PATHS you had in it and i just copied the rest of everything else you had setup, Just few things need help with. How do i get it to look like yours in the "towertheme" yours looked different then mine. You had left columm and right columm with gap and with arrows on all my red ones go out to nothing look in screenshots.


Also neomutt widget isn't working i'm guessing i have to fix paths but i don't know if you can help


<a href="https://imgur.com/d5VM9T6"><img src="https://i.imgur.com/d5VM9T6.png" title="source: imgur.com" /></a>

<a href="https://imgur.com/S3utNQs"><img src="https://i.imgur.com/S3utNQs.png" title="source: imgur.com" /></a>

**Comment by tjw0lf** [comment]
Here's the link i used. i just copied this into neomuttrc and  put back your keybinds and other stuff expect the PATHS of course

https://blog.heila.la/command-line-email-with-neomutt-and-gmail/

**Comment by szorfein** [comment]
good job, you have just used the native imap tools integer in neomutt rather than use offlineimap, it work too.  
The first screenshot is the same as mine, only colors change. the lacking thing on the bottom right is related to the number of postponed message.

**Comment by tjw0lf** [comment]
I thought i was using offlineimap what do you mean how do i use that then

your screenshot is different i want it like yours. not the colors but you have dots beside all your word and arrows and brackets around them all and one side  and other side you have gap inbetween them

**Comment by szorfein** [comment]
Here the differences between native or not:

```sh
# Native IMAP
set imap_user = "[email protected]"
set imap_pass = "YOURSECRETPASSWORD"
set folder = "imaps://imap.gmail.com:993"
# With Offlineimap, only the directory is needed
set folder = ~/.mails

# ---------------------------------------------------------------

# Native SMTP
set smtp_url = "smtp://[email protected]@smtp.gmail.com:587"
set smtp_pass = "YOURSECRETPASSWORD"
# With msmtp, it become
set sendmail="/usr/bin/msmtp"
```
The native solution is nice, too and required less configurations

![](https://i.postimg.cc/43wznj19/Untitled.png)
On the screen, it lack only 3 things, '4' =  Number of deleted messages, the star (1) = Number of flagged messages and Number of postponed messages at right (3)

**Comment by tjw0lf** [comment]
What do i have to do to get what you have? I want mine setup like yours

**Comment by szorfein** [comment]
deleted messages, flagged messages and postponed messages :p

**Comment by tjw0lf** [comment]
Yeah. I want that. Setting up offlineimap. Theres not good guide i can't figure it out. Only way i got to work was screenshot show you.
I just want it like yours :)

If i try the one you have i get that error in terminal i posted above.

**Comment by tjw0lf** [comment]
<a href="https://imgur.com/U5pY3Gk"><img src="https://i.imgur.com/U5pY3Gk.png" title="source: imgur.com" /></a>

I'm Close i just need the star how did you get that. I found this.  i used. there not using offlineimap they say is outdated to old bloat. 

https://github.com/LukeSmithxyz/mutt-wizard = i think my password is secure now it made gpg key i have to do passphrase.

**Comment by szorfein** [comment]
grats! i didn't know mutt-wizard

**Comment by tjw0lf** [comment]
Take crack at it @szorfein  How do i get your star? whats it mean? there not using offlineimap they say its to old bloated. idk. But i know when i tried running it i got python errors if you know what them about

**Comment by szorfein** [comment]
you can make a flagged message by pressing F on a message.  
you can delete a message with dd 

Also you can post your python error if want help about offlineimap. Maybe i would change offlineimap with isync, but later, i will run out of time for testing, I'm going on vacation tomorrow

**Comment by tjw0lf** [comment]
Ok cool. Did you get the widget working doesn't work for me still

Hoe to get star icon you have what do i add?

**Comment by szorfein** [comment]
> Hoe to get star icon you have what do i add

Just create a flagged message with F.  
Eelse can you test the last commit e8e6571 ?  
change the mail directory of course (line 91 and 112), if the popup no working, post the output of your mails directory with the command `tree` plz

**Comment by tjw0lf** [comment]
What does flagged message mean. Does that mean saved it or something else.

I'm not sure which one it is here you go. And here's the offlineimap

<a href="https://imgur.com/vqSQPrF"><img src="https://i.imgur.com/vqSQPrF.png" title="source: imgur.com" /></a>

<a href="https://imgur.com/EKQPYXc"><img src="https://i.imgur.com/EKQPYXc.png" title="source: imgur.com" /></a>

<a href="https://imgur.com/AAI8wH6"><img src="https://i.imgur.com/AAI8wH6.png" title="source: imgur.com" /></a>

<a href="https://imgur.com/sUBJFLN"><img src="https://i.imgur.com/sUBJFLN.png" title="source: imgur.com" /></a>

**Comment by szorfein** [comment]
So, you don't have any mails ?

offlineimap need 

    [Repository Remote]
    sslcacertfile = /etc/ssl/certs/ca-certificates.crt

**Comment by tjw0lf** [comment]
What do i do for widget?  How do i get that file ca-certificates.crt

**Comment by szorfein** [comment]
the mail widget will no work until you have few mails locally.  
the ca-certificates.crt is installed or generate with the package `openssl` normally already installed but the path may change

**Comment by tjw0lf** [comment]
But is mine working? How do i get locally mails

**Comment by tjw0lf** [comment]
OK i didn't install that might be why

**Comment by tjw0lf** [comment]
Well that was  already installed `EDIT: on archlinux, you have to install ca-certificates`

How do i get locally mails?

**Comment by szorfein** [comment]
offlineimap

try install `ca-certificates-utils` too

**Comment by tjw0lf** [comment]
> with offlineimap
> 
> try install `ca-certificates-utils` too, your problem looks like this post https://bbs.archlinux.org/viewtopic.php?id=225590

well that packege is already installed aswell

**Comment by tjw0lf** [comment]
`➜ offlineimap
OfflineIMAP 7.2.4
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v2.57 (bundled), Python v2.7.16, OpenSSL 1.1.1c  28 May 2019
Account sync Gmail:
 *** Processing account Gmail
 Establishing connection to imap.gmail.com:993 (Remote)
 ERROR: Unknown SSL protocol connecting to host 'imap.gmail.com' for repository 'Remote'. OpenSSL responded:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)
 *** Finished account 'Gmail' in 0:00
ERROR: Exceptions occurred during the run!
ERROR: Unknown SSL protocol connecting to host 'imap.gmail.com' for repository 'Remote'. OpenSSL responded:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)

Traceback:
  File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 293, in syncrunner
    self.__sync()
  File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 369, in __sync
    remoterepos.getfolders()
  File "/usr/lib/python2.7/site-packages/offlineimap/repository/IMAP.py", line 452, in getfolders
    imapobj = self.imapserver.acquireconnection()
  File "/usr/lib/python2.7/site-packages/offlineimap/imapserver.py", line 658, in acquireconnection
    exc_info()[2])
  File "/usr/lib/python2.7/site-packages/offlineimap/imapserver.py", line 572, in acquireconnection
    af=self.af,
  File "/usr/lib/python2.7/site-packages/offlineimap/imaplibutil.py", line 194, in __init__
    super(WrappedIMAP4_SSL, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/offlineimap/bundled_imaplib2.py", line 2183, in __init__
    IMAP4.__init__(self, host, port, debug, debug_file, identifier, timeout, debug_buf_lvl)
  File "/usr/lib/python2.7/site-packages/offlineimap/bundled_imaplib2.py", line 361, in __init__
    self.open(host, port)
  File "/usr/lib/python2.7/site-packages/offlineimap/imaplibutil.py", line 202, in open
    super(WrappedIMAP4_SSL, self).open(host, port)
  File "/usr/lib/python2.7/site-packages/offlineimap/bundled_imaplib2.py", line 2196, in open
    self.ssl_wrap_socket()
  File "/usr/lib/python2.7/site-packages/offlineimap/bundled_imaplib2.py", line 548, in ssl_wrap_socket
    self.sock = ssl.wrap_socket(self.sock, self.keyfile, self.certfile, ca_certs=self.ca_certs, cert_reqs=cert_reqs, ssl_version=ssl_version)
  File "/usr/lib/python2.7/ssl.py", line 931, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 599, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 828, in do_handshake
    self._sslobj.do_handshake()
`

**Comment by szorfein** [comment]
need output of 

    ls -la /etc/ssl/certs/ca-certificates.crt

**Comment by tjw0lf** [comment]
```
➜ ls -la /etc/ssl/certs/ca-certificates.crt 
lrwxrwxrwx 1 root root 49 Nov  9  2018 /etc/ssl/certs/ca-certificates.crt -> ../../ca-certificates/extracted/tls-ca-bundle.pem

```

**Comment by szorfein** [comment]
and your offlineimaprc too

**Comment by tjw0lf** [comment]
That's in my $HOME

`➜ ls -la .offlineimaprc
-rw-r--r-- 1 tj users 609 Jul 16 21:21 .offlineimaprc`

Here's what file looks like to

`

[general]
accounts = Gmail
pythonfile = ~/.offlineimap.py

[Account Gmail]
localrepository = Local
remoterepository = Remote

[Repository Local]
type = GmailMaildir
localfolders = ~/.mails/gmail

[Repository Remote]
type = Gmail
auth_mechanisms = LOGIN
remoteuser = wolf.tj996@gmail.com
remotepasseval = get_pass()
#transporttunnel = ssh yagdra@localhost openssl s_client -connect localhost -CApath /etc/ssl/certs -quiet
sslcacertfile = /etc/ssl/certs/ca-certificates.crt`

**Comment by szorfein** [comment]
https://github.com/szorfein/dotfiles/issues/15#issuecomment-511183115

**Comment by tjw0lf** [comment]
i change it. still doesn't work

**Comment by szorfein** [comment]
tjw0lf, u can setup offlineimap yourself, chech their github, there are many post with your problem: 
+ https://github.com/OfflineIMAP/offlineimap/issues 
+ https://github.com/OfflineIMAP/offlineimap/issues/573 , 
+ https://github.com/OfflineIMAP/offlineimap/issues/548 .  

I'm going to run out of time to help you, I may not have internet for 3 weeks during my holidays. I'm sure than you can do it :)
