### ISSUE TITLE
help me with widgets

### ISSUE THREAD

**Issue by tjw0lf** [szorfein/dotfiles#16]
https://github.com/streetturtle/awesome-wm-widgets/tree/master/email-widget

**Comment by szorfein** [comment]
alrealy watch, but yeah, maybe I could write a script myself to see the emails in python or ruby rather than use offlineimap

**Comment by tjw0lf** [comment]
That would be awesome Thanks.

I was trying to find mail widget for gmail. No one has widget

That one is outdated i think. If you can make one like that for gmail circle how many mail you have.

**Comment by tjw0lf** [comment]
Yeah i opened this for another reason. :)

How do i move widget to far left corner of screen. I added widget to battleship.lua. but only seems be in middle or in green line not right want separate. If you get me :)

**Comment by szorfein** [comment]
the bar from the theme battleship is a little weird and uggly, i have to rewrite that :( , the inspiration come from https://www.deviantart.com/inthescene/art/Pines-791144091

**Comment by tjw0lf** [comment]
Its not uggly :) I love battleship. Cool
