### ISSUE TITLE
No icon for workspaces in polybar i3 module, wrong ws name %name% for unfocused and wrong ws order

### ISSUE THREAD

**Issue by mamyn0va** [szorfein/dotfiles#18]
Hi!

First, great job with your themes for i3, it's really nice !

I have issues with i3 module of polybar (see details in the title).

Here is a screenshot.
![Deepin Capture-écran_zone de sélection _20190726154358](https://user-images.githubusercontent.com/11281228/61956043-9b8e0880-afbc-11e9-87ad-90609702264f.png)

Thanks for your support!

**Comment by tjw0lf** [comment]
Can post a screenshot of the terminal output when running polybar.  I'm running this i3 it's amazing @szorfein makes awesome themes.

What app or program are you trying to run.

This is what he told me.
open a terminal in each workspaces to see the name in polybar, my config of polybar only display workspace occupied.

Make sure you have these fonts installed.

```
1. $ wget https://aur.archlinux.org/cgit/aur.git/snapshot/nerd-fonts-noto-sans-regular-complete.tar.gz
2. $ tar xvf nerd-fonts-noto-sans-regular-complete.tar.gz
3. $ cd nerd-fonts-noto-sans-regular-complete
4. $ makepkg -si
```

```
1. $ wget https://aur.archlinux.org/cgit/aur.git/snapshot/ttf-material-icons-git.tar.gz
2. $ tar xvf ttf-material-icons-git.tar.gz
3. $ cd ttf-material-icons-git
4. $ makepkg -si
```

**Comment by szorfein** [comment]
hi,  i read the i3 config, can you edit the file `~/.config/polybar/i3-name` and change the line: 

    8 label-visible = "%icon% %name"

by this:

    8 label-visible = %icon% %name%"

and restart i3 to see if it change something

**Comment by tjw0lf** [comment]
glad your back @szorfein  :D

**Comment by mamyn0va** [comment]
Hi! 

Sorry for the late answer. The icons are working now that I've installed the fonts package.
I still have an issue with the non-focused/visible workspaces, but it must be due to the fact that I'm using an extended desktop, right?

**Comment by szorfein** [comment]
> glad your back @szorfein :D

thanks :)  
Nice for the icon working.   
> but it must be due to the fact that I'm using an extended desktop, right? 

Yep possible, unfortunately, i can't test this, you can see this [issue](https://github.com/polybar/polybar/issues/763) to configure polybar with multiple screen.   

Also, don't hesitate to see the doc at https://github.com/polybar/polybar/wiki/Module:-i3 , you can configure/enhance this theme with your need.
