### ISSUE TITLE
i3-madness, make new icon i3 spaces

### ISSUE THREAD

**Issue by tjw0lf** [szorfein/dotfiles#19]
I'm using firefox and want icon to come up in polybar

`i3-names`

i added 

`ws-icon-6 = firefox;`

But nothing comes up for icon. 

I also added to i3 config

`set $ws6 "firefox"`

There's not icon come up in polybar. How do i do this?

**Comment by szorfein** [comment]
well, it seem to be correct, from the `~/.config/polybar/i3-name` :

    ws-icon-6 = firefox;

from the `~/.config/i3/config`:

    set $ws6 "firefox"
    assign [class="Firefox"] → $ws6

Nothing more, after be sure than your icon is supported by material-icon or any nerd font or add your font in the `~/.config/polybar/i3-top`
