### ISSUE TITLE
totally into Luna

### ISSUE THREAD

**Issue by pjhalsli** [szorfein/dotfiles#2]
....but I miss a vim colorscheme fir luna.  You hsve any  plsmd for it or.................?

**Comment by szorfein** [comment]
thx for u report,  
vim colorscheme for luna ( and all other themes :) ) use [darkest-space](https://github.com/szorfein/darkest-space).  
Normally, the colors do not change much

**Comment by pjhalsli** [comment]
Thank You  :)
I'll close this now
