### ISSUE TITLE
Awesome won't recognize user themes

### ISSUE THREAD

**Issue by halfstrip** [szorfein/dotfiles#20]
Hi, I've installed the tower theme but the theme will not load. I've been searching for fix and apparently awesome keeps loading the default configuration from /etc/xdg/awesome and refuses to load the ~/.config/awesome one.

**Comment by tjw0lf** [comment]
Make sure you have these installed whichever distro you're using.

Ubuntu or Debian
`sudo apt install awesome stow termite compton rofi feh`

st
`sudo apt install stterm`

nerd fonts
`https://github.com/ryanoasis/nerd-fonts`

Arch
`pacman -S git awesome stow termite compton xorg-xinit xorg-server rofi feh`

```
$ cd ~/build
$ wget https://aur.archlinux.org/cgit/aur.git/snapshot/xst-git.tar.gz
$ tar xvf xst-git.tar.gz
$ cd xst-git
$ makepkg -si
And nerd-fonts-iosevka:

$ cd ~/build
$ wget https://aur.archlinux.org/cgit/aur.git/snapshot/nerd-fonts-iosevka.tar.gz
$ tar xvf nerd-fonts-iosevka.tar.gz
$ cd nerd-fonts-iosevka
$ makepkg -si
```

Now download dotfiles and use Stow

`git clone https://github.com/szorfein/dotfiles`
`cd dotfiles`

```
$ stow theme-tower
$ stow awesomewm
$ stow config
$ stow images
```

Now logout switch to awesome you should have theme-tower

**Comment by tjw0lf** [comment]
Hopefully, this helps you out let me know if it works for you.

**Comment by halfstrip** [comment]
Thank you for replying but unfortunately it doesn't seem to work for me. I also tried to install it on my other laptop with manjaro in it but it returns some errors on some line of the .lua file

**Comment by tjw0lf** [comment]
What distro are you using Arch based or Ubuntu based.

my show me screenshot with the errors

**Comment by halfstrip** [comment]
Arch based.

Sorry for being inconsistent but the error doesn't show up anymore after I turn my laptop on. I've got the translucent effect from the theme but not the bar. The bar is just default bar

**Comment by halfstrip** [comment]
I see the error is in env-config.lua in line 20. It failed to index term_call. I don't know why, I've installed xst and add the line export TERMINAL=/usr/bin/xst to .zshrc

**Comment by tjw0lf** [comment]
OK. try this delete the .zshrc. Go into the dotfiles copy .zshrc to $HOME 
try restart awesome. log out back in. See if you have theme-tower

**Comment by szorfein** [comment]
hi, sorry for the delay. the problem can come from the version of awesome, you need the version 4.3.  
also can you post the output of `ls -l ~/.config/awesome` ?

**Comment by tjw0lf** [comment]
@szorfein it's going to automatically install awesome 4.3 because he's on Arch. `pacman -S awesome` to the latest? unless he's using awesome already with an older version 

He did say he tried Manjaro so I'm pretty sure that's awesome 4.3. You got their awesome edition Right? @halfstrip. another thing is make sure you backup there awesome folder and delete it! Then use commands i listed above. it will make the awesome folder when using stow.

**Comment by szorfein** [comment]
no news , i close. Feel free to reopen but it looks like a bad use of stow.
