### ISSUE TITLE
New theme is Awesome

### ISSUE THREAD

**Issue by tjw0lf** [szorfein/dotfiles#21]
Awesome work szorfein. I'm not on Aweosmewm right now :(  I'm on KDE Plasma once i finish some stuff i'm doing i will be joining I like KDE also and i3 and awesomewm and xfce. once i get off i will have to relearn. I just wanted to say hi. how are you doing.

**Comment by szorfein** [comment]
hi thanks, it's been a long time :) new theme-morpho out.  For the next, i will probably add a lock screen based on elenapan (https://camo.githubusercontent.com/0f55f981a874a9d2c02d9a67a8aefd984b7228a0/68747470733a2f2f692e696d6775722e636f6d2f424c30555341482e706e67) and look for make an app drawer (https://camo.githubusercontent.com/eba23992df5ee42f9746ca6c2fe7792088c91419/68747470733a2f2f692e696d6775722e636f6d2f5a3572595576492e706e67) but maybe more text based, well see.  
Else i'm learning how to use docker, kubernetes, rails and vuejs, it will take time too :)

**Comment by tjw0lf** [comment]
Cool Awesome.  If your able to spice up the menu in theme-morpho. on right click that would be cool round corners as well.

**Comment by szorfein** [comment]
yep good idea, but after reading the [API](https://awesomewm.org/doc/api/libraries/awful.menu.html), it does not seem possible to add a `shape` to menu, maybe later :)
