### ISSUE TITLE
Some icons on footer and left bar not working properly

### ISSUE THREAD

**Issue by 4SW3** [szorfein/dotfiles#22]
Hey first and foremost thanks for sharing this awesome theme, I recently (2 days ago) installed Arch and Awesome WM and was looking for a theme and then I ended up finding this repo.

I got morpho installed with success but some icons, buttons, bars seems to not be working properly for me. I was able to fix some of the stuff such as the network and processor in the footer but most of them still needs to be fixed. 

Here is a print to help visualize the issues: https://imgur.com/X6jwkHx

Since I don't know anything about lua, it's hard to know where I need to look at in order to fix the issues.

So, so far the stuffs that are not working for me is:
  -the left bar sound slider
  -some footer icons not displaying (also I would like to increase a bit the font size) because the icons are too small
  -github, reddit, twitter buttons on start screen not working (maybe I need to set firefox as my default browser for WM I think I haven't done that yet)
  -still in start screen, as I would expect the images, torrents, movies aren't working. Are you using another graphical user interface together with Awesome WM to display this? 
  -the lock screen, after I unlock it with password the lock window overlay won't go away, so I have to restart the WM in order to get rid of it.

Sorry for the text wall and thanks again for this amazing theme, you made me want to learn lua which is something I plan on doing after I finish my js project.

**Comment by szorfein** [comment]
thanks for the issue, i'll make some commit in the next few days, there will be plenty of things to fix :)

In resume:
+ the left bar sound slider - do you use pulseaudio? you have to configure correctly the default device with 'set-default-sink' (https://wiki.archlinux.org/index.php/PulseAudio)
+ github, reddit, twitter buttons on start screen not working - The default try to launch 'brave', i will correct this too
+ the lock screen - weird, it work fine for me, you type the default pass 'awesome' and 'enter'. 
+ start screen, as I would expect the images, torrents, movies - the default use 'nnn', i have to make this customizable too, what do you use as file browser?

**Comment by 4SW3** [comment]
thanks for the reply.
I haven't installed yet any file manager, but I decided to test 'nnn'. Now it's working fine. 

The lock screen was my mistake, I was entering the wrong password xD. But I think I found a bug, if I miss the password the overlay screen doesn't go away, but ... I can still have control of my desktop, I can do for example 'super + w' and restart awesome wm even with the screen locked.

About the link buttons ... I found the right file and hardcoded it to /usr/bin/firefox and now its fixed.

I'm using 'Alsa' for the sound, it's the default for arch so it just needs to be unmuted with amixer or alsamixer (I choose alsamixer).

So the 2 main things I still need to fix is the sound slider and the footer icons. Also where can I increase the font size, the icons are too small for my screen.

**Comment by szorfein** [comment]
for the footer icons, edit the file: ~/.config/awesome/themes/morpho/theme.lua and change:

    theme.widget_icon_font = theme.myfont.." Mono 12" 

Just increase the number here :)  

About alsa, you have to change the `env.sound_card_alsa = "hw:Pro"` from the `env.config`, you can try, it depend of your system:

+ env.sound_card_alsa = "default:PCH"
+ env.sound_card_alsa = "default"

Card name can be found with:
```
 $ cat /proc/asound/cards
 0 [Loopback       ]: Loopback - Loopback
                      Loopback 1
 1 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xd0810000 irq 93
 2 [Pro            ]: USB-Audio - SB X-Fi Surround 5.1 Pro
                      Creative Technology Ltd SB X-Fi Surround 5.1 Pro at usb-0000:00:14.0-1, full sp
```
I use the 2 [Pro ], so for me, it's env.sound_card_alsa = "hw:Pro".

**Comment by 4SW3** [comment]
Thanks, the icons are now okay for me.

About alsa, I changed it to default but it still didn't work. I noticed there are some lines of code with "amixer -D" in: 
  /awesome/daemons/volume.lua  -> line 10
  /awesome/keys.lua -> lines 195, 202
  /awesome/widgets/volume.lua -> line 69

Since I'm using alsamixer to manage the volume, I changed it to alsamixer -D default but still no success, any thoughts?

**Comment by szorfein** [comment]
Unfortunately, there are no way to use alsamixer with the command line. You can test in a terminal to see the debug message with and without the -D option like:
  
    amixer -D 'hw:loopback' sset Master 10%
    amixer set Master 5%+
    amixer set Master 5%-

Look at https://wiki.archlinux.org/index.php/Advanced_Linux_Sound_Architecture for help with amixer

**Comment by 4SW3** [comment]
Got it, I thought I could set this up with alsamixer because when I type on terminal "alsamixer -D default", it opens up the sound config for my default device. Anyway I reverted it back to amixer and now it's working. 

The other thing I'll have to fix is the middle icons on the footer (https://imgur.com/X6jwkHx), 2 icons aren't showing up and 1 is unknown but I think it has something to do with the fact that I'm in desktop. I'll see tomorrow if I can hardcode it to a static icon or maybe remove the battery/brightness bars.

**Comment by 4SW3** [comment]
Before I had replaced 'unknown' with another Icon but I changed here to look similar to yours, thanks.
Now there's just  [this](https://i.imgur.com/IFGqxJz.png) brightness icon issue.

Also do you know why the glyph/icons size are too small on terminal? [e.g](https://imgur.com/cyX1F9S)

**Comment by szorfein** [comment]
Your icon size seem related to ryanoasis/nerd-fonts#127, you can try with an other terminal or try differents nerd font.  
About the brightness icon, no idea why it didn't display, you can try to increase the widget size in ~/.config/awesome/bars/morpho.lua 
  
          108    boxes(widget.box('vertical', { w1, w2 }), 360),

And i found your icons very small in the awesome widgets :)

**Comment by 4SW3** [comment]
Yeah I figured it would be related to the font as well, I'm gonna try with other fonts later.
About the brightness, I found a workaround but maybe the issue is related to notebook as well (similar to the battery thing). And yeah I just increased a bit the icon size.

Anyway, if I find any other bugs/issues I'll let you know and I'll also be looking forward for future updates and releases, thanks.

**Comment by 4SW3** [comment]
Hi again, I think I found a small bug with morpho. 
If I toggle floating `super + s` and then maximize/unmaximize the window `super + m`, the borders seems to dissapears.  [This print shows well](https://imgur.com/xiRj8za)

I also installed rofi to use with your theme and I had to replace `"launcher"` on keys.lua with the following below, because for some reason it wasn't opening.
`key({ modkey }, "p", function() awful.spawn("rofi -show run") end,`

**Comment by szorfein** [comment]
the launcher script is in your `~/bin` directory normally, awesome don't see it unless you add the directory to your PATH variable somewhere in your zshrc or bashrc:  

    export PATH=$HOME/bin:$PATH

I will update the wiki page :)  
And about the border, yep it's happen sometime, i have too look how correct that.

**Comment by 4SW3** [comment]
got it thanks
