### ISSUE TITLE
Multiple monitor issue

### ISSUE THREAD

**Issue by k4rz4** [szorfein/dotfiles#23]
Hi, 

I have 3 monitors, and on one workspace i get 3 sidebars 

![awesome](https://user-images.githubusercontent.com/18619978/70451325-73073680-1aa5-11ea-84bf-b982156285a6.png)

**Comment by szorfein** [comment]
weird, i will looking how to fix that :)

**Comment by szorfein** [comment]
the problem exist on the last theme morpho too? i can't test myself

**Comment by szorfein** [comment]
the default rc use this:

    -- Create the wibox
    s.mywibox = awful.wibar({ position = "top", screen = s })

Try to add `screen = s` at `~/.config/awesome/bars/machine.lua` like this:

      s.mywibox = awful.wibar({ position = beautiful.wibar_position, width = beautiful.wibar_size, bg = beautiful.wibar_bg, screen = s })

**Comment by k4rz4** [comment]
> 
> 
> the problem exist on the last theme morpho too? i can't test myself

On every theme that has sidebar. 


> 
> 
> the default rc use this:
> 
> ```
> -- Create the wibox
> s.mywibox = awful.wibar({ position = "top", screen = s })
> ```
> 
> Try to add `screen = s` at `~/.config/awesome/bars/machine.lua` like this:
> 
> ```
>   s.mywibox = awful.wibar({ position = beautiful.wibar_position, width = beautiful.wibar_size, bg = beautiful.wibar_bg, screen = s })
> ```

Letting you know tonight, wasn't online few days . Thanks!

**Comment by szorfein** [comment]
the two last commit 77df187 and 351097a should solve this issue if you can test (unless i've missed something:)
