### ISSUE TITLE
brick my kde

### ISSUE THREAD

**Issue by najamsk** [szorfein/dotfiles#24]
i am using opensuse and tumbleweed.

I love your themes and wanted to try with my awesomewm setup.

tried stow stuff cant get it work and now cant login to my kde either. Can you please provide simple installation guide. or installing without stow. 

Again love your RICE.

**Comment by szorfein** [comment]
hi, thanks you.  
Do you see the wiki for arch, https://github.com/szorfein/dotfiles/wiki/theme-anonymous ? 

Also, It doesn't work (not tested) with SDDM / GDM, etc. I use xinit to start my session simply with `startx`.  
You can try to kill / uninstall your display manager .

With SDDM, you may need to add the entry for awesome : https://github.com/sddm/sddm/issues/868

**Comment by najamsk** [comment]
> hi, thanks you.
> Do you see the wiki for arch, https://github.com/szorfein/dotfiles/wiki/theme-anonymous ?
> 
> Also, It doesn't work (not tested) with SDDM / GDM, etc. I use xinit to start my session simply with `startx`.
> You can try to kill / uninstall your display manager .
> 
> With SDDM, you may need to add the entry for awesome : [sddm/sddm#868](https://github.com/sddm/sddm/issues/868)

i found one page where kill command and startx was shown and atleast kde seems to be back.
I might be super wrong since I am way noob in linux stuff compare to you. My understanding is you are coping stuff from your dot files to home folder. 

like stow theme-anonmoys -t ~/.config/awesome/ 

that will install it your files inside my awesome directory? i think i broke stuff when i copied to home folder.  since my main DE is kde i want only files inside ~/.config/awesomewm how do i do that. 
also i was not able to see rc.lua files after running stow commands

**Comment by najamsk** [comment]
stow images

also when run this it says images package is not installed or not found.

**Comment by szorfein** [comment]
I will update the wiki :)  
there is no more image folder, he alone made more than 50 mo with the git cache. To install the last images, do a 

    ./install --images

In the directory of this repo.

> like stow theme-anonmoys -t ~/.config/awesome/

No, the directory target (with ~t) is always your $HOME , so `~` or `/home/najamsk`. so the corrected command are: 

    $ stow awesomewm -t ~
    $ stow theme-anonymous -t ~

It will install color for the Xresources, color for zathura, etc, (look this content).

For KDM, the wiki of [archlinux](https://wiki.archlinux.org/index.php/Awesome) suggest this:

Create as root /usr/share/apps/kdm/sessions/awesome.desktop

```txt
[Desktop Entry]
Name=Awesome
Comment=Tiling Window Manager
Type=Application
Exec=/usr/bin/awesome
TryExec=/usr/bin/awesome
```
