### ISSUE TITLE
Miami Theme on awesomewm has weird fonts

### ISSUE THREAD

**Issue by beeaniebee** [szorfein/dotfiles#25]
I've just installed the miami theme onto a fresh void linux install. The titlebar and the topbar have what looks like simple Times New Roman font, when I don't think it should. I've been going over the config files, and other references in other closed issues for about an hour now, and can't figure this out. Anyone have a fix? Am I just missing a font? Picture attached.
![fontnotworking](https://user-images.githubusercontent.com/29309688/81381125-223e4d00-90da-11ea-8de5-1bd3dccfdb5a.png)

**Comment by szorfein** [comment]
Cool, it's work on void, I'll test the system later unless I test KISS, we'll see :)

The code for:
+ the fonts, it's [here](https://github.com/szorfein/dotfiles/blob/master/theme-miami/.config/awesome/loaded-theme.lua)
+ the titlebar, [here](https://github.com/szorfein/dotfiles/blob/master/awesomewm/.config/awesome/titlebars/smart-border.lua)

The titlebar use the font name `subtile_1`, so it's `subtile_1 = "Space Mono Nerd Font Complete Mono 13",`

Try to look is the font name match on void, something like:

    $ fc-match -a | grep -i "space"

**Comment by beeaniebee** [comment]
I downloaded the “Space Mono Nerd Font” from the nerdfonts website and put the files into the ~/.fonts folder. Is there another place I need to put it in?

`$ fc-match -a | grep “space”` returned nothing, but using a capital S did.

**Comment by szorfein** [comment]
you can install the font at `~/.local/share/fonts` and reload the cache with

    $ fc-cache -vf ~/.local/share/fonts

After this, reload awesome and it should work.

**Comment by beeaniebee** [comment]
That didn’t work either! What‘s your output for `fc-match -a | grep -i “space”`

**Comment by szorfein** [comment]
When the font is correctly installed, it should return this:

    $ fc-match -a | grep -i space

```txt
Space Mono Nerd Font Complete Mono.ttf: "SpaceMono Nerd Font Mono" "Regular"
Space Mono Nerd Font Complete.ttf: "SpaceMono Nerd Font" "Regular"
Space Mono Bold Nerd Font Complete Mono.ttf: "SpaceMono Nerd Font Mono" "Bold"
Space Mono Bold Nerd Font Complete.ttf: "SpaceMono Nerd Font" "Bold"
Space Mono Italic Nerd Font Complete Mono.ttf: "SpaceMono Nerd Font Mono" "Italic"
Space Mono Italic Nerd Font Complete.ttf: "SpaceMono Nerd Font" "Italic"
Space Mono Bold Italic Nerd Font Complete Mono.ttf: "SpaceMono Nerd Font Mono" "Bold Italic"
Space Mono Bold Italic Nerd Font Complete.ttf: "SpaceMono Nerd Font" "Bold Italic"
```

Maybe that void linux does things differently, at worst try to make a real package spacemono-nerd-font in a custom repo https://docs.voidlinux.org/xbps/repositories/custom.html :)
