### ISSUE TITLE
Stolen work from you!

### ISSUE THREAD

**Issue by G-Rowell** [szorfein/dotfiles#26]
Hi,

your repo here,

Has been stolen & re-uploaded by the GitHub user: https://github.com/5R33CH4

Here is their repo in which they've stolen your work, and attributed it to themselves: https://github.com/5R33CH4/dotfiles

They also have a GitHub org, where they also have some stolen work: https://github.com/tesseract-org.

Checkout their all their personal repos...

I'm sorry to bring you this bad news, this user has stolen >50 repos so you should consider reporting them to GitHub.

Galen

**Comment by szorfein** [comment]
Hi, sorry for the late answer and thanks you for reporting this.

**Comment by G-Rowell** [comment]
No problem,

the user took down a portion of the stolen work and faked being hacked.
Seems solved though, my apologies for the bad news.

Take care & have a good night!
