### ISSUE TITLE
Rofi issue

### ISSUE THREAD

**Issue by 0xSnoxzy** [szorfein/dotfiles#29]
Sorry if i'm opening another issue but installation went very well, but when i do SuperKey+R to open the rofi menu it gives me this error:

```The following errors were detected when starting rofi:

/home/(my username)/.config/rofi/config.rasi:2:34: Option: font needs to be set with a string not a Reference.

/home/(my username)/.config/rofi/config.rasi:8:23: The option:

configuration
{
           theme:"./theme.rasi":
}
is deprecated. please replace with: @theme "./theme.rasi" after the configuration block.
```

Is there any way you could help me? It would be very appreciated :D

**Comment by szorfein** [comment]
> Sorry if i'm opening another issue

No problem, it will helps me to update some things :)

I tried using rofi for a while but i'm not a huge fan, i always find it too slow and too complicated to configure. I prefer using simple tools like dmenu to launch app so i will probably remove any configs of rofi here.
