### ISSUE TITLE
Stupid quest

### ISSUE THREAD

**Issue by ElModdy** [szorfein/dotfiles#3]
Hi, I'm sorry for the stupid quest feel free to close the issue.
Is there a way to syslink the whole folder with stow, so when I add a file in the "original" directory it gets created also in the .dotfiles repo?

**Comment by szorfein** [comment]
what do you try to do?  
You can create a new directory outside your home directory, for example /home/my-dots,   
you paste behind all the files you want, and create a simple link with:
    
    $ ln -s /home/my-dots /home/username

 (the directory should be void) , the permission on the `/home/my-dots` will be less secure 0770.  

With only stow, it's a bit more complicated to do.
