### ISSUE TITLE
configuration error?

### ISSUE THREAD

**Issue by rdtor** [szorfein/dotfiles#4]
Hi feel free to close the issue, its regarding How to setup the dotfile  , first of thank you for this , it looks aweosme i been trying to setup  followng the instruction. i feel stuck, tow: ERROR: The stow directory szorfein/dotfiles does not contain package image, i have cloned your repository to home directory.

**Comment by szorfein** [comment]
thanks, what theme do you try to use?

**Comment by rdtor** [comment]
all of them looks amazing, i would like to try theme
-madness

**Comment by szorfein** [comment]
I've tested and found a font error with subtle. It should work now with subtle and i3-gaps.
    
    $ stow config
    $ stow images
    $ stow theme-madness

You need dina font too.

**Comment by szorfein** [comment]
no news, i close :), thx for issue
