### ISSUE TITLE
awesome wm theme

### ISSUE THREAD

**Issue by najamsk** [szorfein/dotfiles#5]
hi i love your ricing. i like to try your new anonymous theme. i tried copy pasting files to my awesome folder but it throws lots of errors. i then install stow and when try to follow instruction provided on github page it says conflicts as target is not directory. 

hoping for some help here. again great stuff.

Thanks, 
Najam

**Comment by szorfein** [comment]
hi, thanks! 

I will reorder my dotfiles soon, the directory `config` contain too many things (in the next commit).  
For now, you need install 3 directory with stow:

+ `awesomewm`: if you have alrealy a directory, you should backup:

    $ cd ~/.config
    $ mv awesome awesome-backup
    $ cd ~/dotfiles
    $ stow awesomewm -t ~

+ `config` , there are many files here, for now, you can remove few dirs:

    $ cd ~/dotfiles/config
    $ rm .spectrwm.conf 
    $ rm -rf .config/{bspwm,herbstluftwm,lemonbar,mpv,neofetch,ranger,sxhkd}

You have just to backup the rest (xinit, Xresources), the install with stow should be less verbose :)

+ `images`  and `theme-anonymous` should be ok
