### ISSUE TITLE
Beginner Question

### ISSUE THREAD

**Issue by awalvie** [szorfein/dotfiles#6]
Hi, 

I have a very basic rice on my (KDE Plasma) Manjaro right now and have been contemplating to move to i3 for a while now. The thing is, I really like your dotfiles, but I don't really know how I am supposed to start, in that, what *nix am I supposed to have and how to go about installing this on a fresh machine. Could you please help me out by pointing out the steps that I should take to go about installing it in a beginner friendly fashion ?

**Comment by szorfein** [comment]
no problem, what theme would you like to try first?

**Comment by awalvie** [comment]
The first one, anonymous

**Comment by szorfein** [comment]
first version:

## install on manjaro linux

## 1st, Open a terminal

just open a terminal :)

## 2nd dependencies
Official packages:

    sudo pacman -S stow awesome xorg-xinit git rofi compton feh

From AUR (with [manjaro](https://wiki.manjaro.org/index.php?title=Arch_User_Repository):

    sudo pamac build nerd-fonts-iosevka nerd-fonts-roboto-mono xst-git 

## my repos

    cd
    git clone https://github.com/szorfein/dotfiles
    cd dotfiles

## stow

    stow config
    stow images
    stow awesomewm
    stow theme-anonymous

if a file alrealy exist, `stow` will show you what you have to move, example:

    stow config
    WARNING! stowing config would cause conflicts:
      * existing target is neither a link nor a directory: .Xresources
      * existing target is neither a link nor a directory: .xinitrc
    All operations aborted.

Here, you have to backup the files `.Xresources` and `.xinitrc`

    mv ~/.Xresources ~/.Xresources-BACKUP
    mv ~/.xinitrc ~/.xinitrc-BACKUP

And relaunch stow to see if it's right now.

    stow config

## shell
If your shell is bash, edit the file `~/.bashrc`, for zsh, edit `~/.zshrc` and add xst or the terminal than you use:

    TERMINAL=/usr/bin/xst

## Kill current X session

    pkill X

## Start with my files

    startx

**Comment by awalvie** [comment]
First of all thank you for writing such detailed instructions, I'll try this as soon as possible

**Comment by szorfein** [comment]
np, just let me know if something is wrong or doesn't work :)

**Comment by awalvie** [comment]
I'll try this out in just a couple of days, I have super crap internet right now.

**Comment by awalvie** [comment]
Tried it out and it works perfectly.
