### ISSUE TITLE
unlinking is not working?

### ISSUE THREAD

**Issue by tjw0lf** [szorfein/dotfiles#8]
I did stow -D images/ in my $HOME not un symlinking

**Comment by szorfein** [comment]
you should go  in the directory of dotfiles before:

    $ cd dotfiles
    $ stow -D images

**Comment by tjw0lf** [comment]
Just out of curiosity. What if i what to do ALL in dotfiles then what to do :).

**Comment by szorfein** [comment]
Well, we have to write a little script because it's really boring to do manually :)

`stow -D on each directory used` and restore each files `mv ~/file-BACKUP ~/file`...
