### ISSUE TITLE
Just so you know this doesn't work??

### ISSUE THREAD

**Issue by tjw0lf** [szorfein/dotfiles#9]
The .zshrc too to run xst rather than the default xterm:

$ echo "export TERMINAL=/usr/bin/xst" > .zshrc

JUST DELETES EVERYTHING in .zshrc... That command doesn't work anywhy lol

**Comment by szorfein** [comment]
> $ echo "export TERMINAL=/usr/bin/xst" > .zshrc

Yep, the title is `Install the theme-anonymous on a fresh install of archlinux─` So, i assume than the `.zshrc` doesn't exist before enter the command.  
But i will update the wiki for people who enter command without reflexion :)  

So the good command is:

    $ echo "export TERMINAL=/usr/bin/xst" >> .zshrc

**Comment by tjw0lf** [comment]
Nope doesn't work?

**Comment by szorfein** [comment]
you should source the file too:

    $ source .zshrc

And look if the variable is change:

    $ env | grep -i terminal
    TERMINAL=/usr/bin/xst

**Comment by tjw0lf** [comment]
I did that output was the same. tried it again that way does not work. I went into the `env-config.lua` changed xterm to xst and worked for me. Thank you

**Comment by szorfein** [comment]
ok thanks, it's weird that it doesn't work for you, maybe i will change the default xterm with xst, xst is easy to install and work better than xterm (utf-8 support) for my dots.

**Comment by tjw0lf** [comment]
Yeah i really like xst :)
